framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    # https://symfony.com/doc/current/messenger.html#transport-configuration
    transports:
      amqp_row_proceed:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%/messages'
        options:
          exchange:
            name: row_proceed
            type: fanout
          queues:
            row_queue: ~
        retry_strategy:
          max_retries: 0

    routing:
      # Route your messages to the transports
      'App\Message\RowMessage': amqp_row_proceed
