version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"

  php:
    container_name: php
    build: .
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/app
    depends_on:
      - mysql
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
    ports:
      - "443:8000"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    environment:
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"
