App\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 50
    description:
      - NotBlank: ~
      - Length:
          max: 255
    code:
      - NotBlank: ~
      - Length:
          max: 10
    stock:
      - GreaterThan: 0
    cost:
      - GreaterThan: 0
      - LessThanOrEqual: 1000
  constraints:
    - App\Validator\Product\PriceConstraint: ~
